# Generated by Django 2.2.2 on 2020-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_items',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=None)),
            ],
        ),
    ]
