# Generated by Django 2.2.2 on 2020-04-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_items',
            new_name='Food_item',
        ),
    ]
