# Generated by Django 2.2.2 on 2020-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_auto_20200430_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('order_status', models.IntegerField(default=None)),
            ],
        ),
    ]
