# Generated by Django 2.2.2 on 2020-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('destination', models.CharField(default=None, max_length=100)),
                ('vehicle', models.CharField(default=None, max_length=100)),
                ('present_time', models.TimeField(default=None)),
                ('arrival_time', models.TimeField(default=None)),
                ('departure_time', models.TimeField(default=None)),
                ('full_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
