# Generated by Django 2.2.2 on 2020-04-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
        migrations.AddField(
            model_name='files',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
