# Generated by Django 2.2.2 on 2020-04-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200429_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('food_id', models.IntegerField(default=None)),
                ('quantity', models.IntegerField(default=None)),
            ],
        ),
    ]
