# Generated by Django 2.2.2 on 2020-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Granted_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('full_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('full_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(default=None)),
            ],
        ),
    ]
