# Generated by Django 2.2.2 on 2020-04-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile2',
        ),
    ]
